name: da1
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
    sdk: ^3.7.0

dependencies:
    flutter:
        sdk: flutter
    cupertino_icons: ^1.0.8
    lucide_icons_flutter: ^3.1.4
    flutter_bloc: ^8.1.2
    dio: ^5.3.3
    equatable: ^2.0.5
    go_router: ^16.2.1
    flutter_signin_button: ^2.1.1
    flutter_screenutil: ^5.9.3
    font_awesome_flutter: ^10.9.1
    syncfusion_flutter_gauges: ^31.1.19
    fl_chart: ^1.1.1
    flutter_secure_storage: ^9.2.4
    dartz: ^0.10.1
    intl: ^0.20.2
    jwt_decoder: ^2.0.1
    url_launcher: ^6.3.1
    app_links: ^6.3.4
    supabase_flutter: ^2.9.4
    flutter_dotenv: ^6.0.0

dev_dependencies:
    flutter_test:
        sdk: flutter
    integration_test:
        sdk: flutter

    flutter_lints: ^5.0.0

flutter:
    uses-material-design: true
    assets:
        - .env
        - assets/images/welcome1.jpeg
        - assets/images/welcome2.jpeg
        - assets/images/welcome3.jpeg
